In [2]:
# numpy 관련
import numpy as np

In [17]:
arr = np.arange(15)
print(arr, type(arr)) # array 
arr = arr.reshape(3,5) # reshape: 배열 재정의
print(arr, arr.ndim) # ndim 몇 차원인지
print(arr.shape, arr.size, arr.dtype.name) # shape(3 * 5)
print(arr.dtype.itemsize) # 데이터의 저장 공간 사이즈 : 4byte

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 2
(3, 5) 15 int64
8


In [26]:
arr = np.arange(-5,5,0.5)
arr = arr.reshape(4, int(arr.size / 4)) # reshape 차수 변경 할 때
print(arr)
arr1 = arr.flatten() # 다차원을 1차원으로 변형
arr1.ndim

[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]]


1

In [36]:
# 기존의 파이썬 리스트로 array 생성

list_a = np.array([1,2,3,4]) 
list_b = np.array([[1,2,3], [4,5,6]])
print('list_a : {}, list_a의 type : {}'.format(list_a, type(list_a)))
print('list_b : {}, list_b의 type : {}'.format(list_b, type(list_b)))
print('list_a dim : {}, list_a의 shape : {}'.format(list_a.ndim, list_a.shape))
print('list_b dim : {}, list_b의 shape : {}'.format(list_b.ndim, list_b.shape))
print('list_a의 size {}, list_a의 dtype {}'.format(list_a.size, list_a.dtype))





list_a : [1 2 3 4], list_a의 type : <class 'numpy.ndarray'>
list_b : [[1 2 3]
 [4 5 6]], list_b의 type : <class 'numpy.ndarray'>
list_a dim : 1, list_a의 shape : (4,)
list_b dim : 2, list_b의 shape : (2, 3)
list_a의 size 4, list_a의 dtype int64


In [ ]:
# np.arange([start], stop, [step])
# np.array.reshape(차수, ...), np.flatten() 1차원으로 변경
# np.ndim, np.shape, np.dype, np.dtpye.name, np.size

In [16]:
# 배열을 생성하면서 값을 초기화 하는 방법 : zeros(), ones()
a = np.zeros(5)
print(a)

b = np.zeros((2,3))
print(b)
print(np.zeros((5,2), dtype='i'))
print(np.zeros(5, dtype='U4'))
print(np.ones((2,3,4), dtype='i8'))
print(np.ones_like(b, dtype='f'))
print(np.empty((4,3)))
print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
['' '' '' '' '']
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[  0.  inf -inf  nan]


/var/folders/8x/my7blpjs0bg1hmjhzgvz02th0000gn/T/ipykernel_1474/2011724948.py:11: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))
/var/folders/8x/my7blpjs0bg1hmjhzgvz02th0000gn/T/ipykernel_1474/2011724948.py:11: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0,1,-1,0]) / np.array([1,0,0,0]))


In [17]:
x2 = np.array([-1.0, -2.0])
z1 = np.array([[5.0], [10.0], [15.0]])
x2 + z1

array([[ 4.,  3.],
       [ 9.,  8.],
       [14., 13.]])

In [38]:
# numpy indexing, slicing, iterating

arr = np.arange(10) ** 2
print(arr)
print(arr[2])
print(arr[3:5])
arr[0:6:2] = -arr[0:6:2]
print(arr)
print(arr[ : : -1])
for i in arr:
    print(i, end='\t')

    
arr = np.arange(1, 21, 1).reshape(4, 5)
print(arr)
print(arr[3,4])
print(arr[0:3, 1:]) # 0:3 0행부터 2행까지 3은 포함하지 않음
print(arr[1, ]) # 1행 출력
print(arr[-1, ]) # 마지막행 출력

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0   1  -4   9 -16  25  36  49  64  81]
[ 81  64  49  36  25 -16   9  -4   1   0]
0	1	-4	9	-16	25	36	49	64	81	[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
20
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
[ 6  7  8  9 10]
[16 17 18 19 20]


In [42]:
# numpy 일반 함수
# np.cos(), sin(), tanh(), exp()
arr = np.arange(0, 6, 1)
print(arr, np.cos(arr), np.sin(arr), np.tanh(arr), np.exp(arr))

arr = np.arange(0.01, 1, 0.05)
print(np.log(arr))

[0 1 2 3 4 5] [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] [0.         0.76159416 0.96402758 0.99505475 0.9993293  0.9999092 ] [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[-4.60517019 -2.81341072 -2.20727491 -1.83258146 -1.56064775 -1.34707365
 -1.17118298 -1.02165125 -0.89159812 -0.77652879 -0.67334455 -0.5798185
 -0.49429632 -0.41551544 -0.34249031 -0.27443685 -0.21072103 -0.15082289
 -0.09431068 -0.04082199]


In [84]:
arr1 = np.array([2,3,4])
arr2 = np.array([5,1,2])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))
print(np.sum(arr1))
print(np.random.choice(45, 5),flush=True) # 0~100 사이의수 중에서 5개 출력
print(np.random.rand(2, 3)) # 2행 3열의 random 값 리턴
print(np.random.randn(2, 3)) # 2행 3열의 random 값 리턴(-1부터 1까지의 float)

# 위치를 반환하는 함수 argmax, argmin
arr = np.array([6,2,1,5,4])
print(np.argmax(arr), ':', arr[np.argmax(arr)])


arr3 = np.array([[0.1, 0.8, 0.2], [0.3, 0.6, 0.1], [0.9, 0.8, 0.7]])
print(arr3)
print(np.argmax(arr3, axis=1))
print(np.argmax(arr3, axis=0))





[5 3 4]
[2 1 2]
9
[23  8  3 32  4]
[[0.71202973 0.10886453 0.38894514]
 [0.88296509 0.47816152 0.33945885]]
[[-0.43010217  0.31275276 -0.40511931]
 [-0.68464696 -0.24001679 -0.07654084]]
0 : 6
[[0.1 0.8 0.2]
 [0.3 0.6 0.1]
 [0.9 0.8 0.7]]
[1 1 0]
[2 0 2]


In [88]:
# 기술 통계 함수
# count(), mean(), var(), std(), median(), max(), min(), percetile()

arr = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
               2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])
print(len(arr)) # 갯수
print(np.mean(arr)) # 평균
print(np.var(arr)) # 분산
print(np.std(arr)) # 표준편차
print(np.max(arr)) # 최대값
print(np.min(arr)) # 최소값
print(np.median(arr)) # 중앙값
print(np.percentile(arr, 25)) # 1 사분위의 수
print(np.percentile(arr, 50)) # 2 사분위의 수
print(np.percentile(arr, 100)) # 최대 값

26
4.8076923076923075
115.23224852071006
10.734628476137871
23
-24
5.0
0.0
5.0
23.0


In [117]:
# 난수 발생과 카운팅
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [127]:
# 데이터 순서를 바꾸는 방법
arr = np.arange(11)
print(arr)
print(np.random.shuffle(arr)) # arr 자료의 순서를 바꿈
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]
None
[ 8  1  5  2  0  6  7  9  3 10  4]


In [175]:
# 샘플링 : choice()
np.random.choice(46, 5, replace=False) # shuffle 과 같은 결과
np.random.choice(10, 3, replace=False) # 10개 중 3개만 선택
np.random.choice(5, 10) # 5개 숫자에서 10개를 추출 : 중복 허용
np.random.choice(5, 10, p=[0.1, 0.3, 0.5, 0.2, 0]) # 선택확률을 다르게

array([2, 4, 8])

In [180]:
# randint() 정수 난수 발생 numpy.random.radint(low, high=None, size=None)
np.random.randint(10, size=10) # 10은 포함하지 않음
np.random.randint(10, 20, size=10) # 20은 포함하지 않음
np.random.randint(10, 20, size=(3,5)) # 3행 5열의 array 반환

array([[13, 15, 12, 10, 11],
       [14, 10, 15, 18, 13],
       [19, 11, 15, 19, 10]])

In [200]:
x = np.arange(1, 21)
x[ x % 3 == 0]
x[ x % 4 == 1]
x[ (x % 3 == 0) & (x % 4 == 1)]

array([9])