In [1]:
# numpy 관련
import numpy as np

In [17]:
arr = np.arange(15)
print(arr, type(arr)) # array 
arr = arr.reshape(3,5) # reshape: 배열 재정의
print(arr, arr.ndim) # ndim 몇 차원인지
print(arr.shape, arr.size, arr.dtype.name) # shape(3 * 5)
print(arr.dtype.itemsize) # 데이터의 저장 공간 사이즈 : 4byte

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 2
(3, 5) 15 int64
8


In [26]:
arr = np.arange(-5,5,0.5)
arr = arr.reshape(4, int(arr.size / 4))
print(arr)
arr1 = arr.flatten() # 다차원을 1차원으로 변형
arr1.ndim

[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]]


1

In [36]:
# 기존의 파이썬 리스트로 array 생성

list_a = np.array([1,2,3,4]) 
list_b = np.array([[1,2,3], [4,5,6]])
print('list_a : {}, list_a의 type : {}'.format(list_a, type(list_a)))
print('list_b : {}, list_b의 type : {}'.format(list_b, type(list_b)))
print('list_a dim : {}, list_a의 shape : {}'.format(list_a.ndim, list_a.shape))
print('list_b dim : {}, list_b의 shape : {}'.format(list_b.ndim, list_b.shape))
print('list_a의 size {}, list_a의 dtype {}'.format(list_a.size, list_a.dtype))





list_a : [1 2 3 4], list_a의 type : <class 'numpy.ndarray'>
list_b : [[1 2 3]
 [4 5 6]], list_b의 type : <class 'numpy.ndarray'>
list_a dim : 1, list_a의 shape : (4,)
list_b dim : 2, list_b의 shape : (2, 3)
list_a의 size 4, list_a의 dtype int64


In [ ]:
# np.arange([start], stop, [step])
# np.array.reshape(차수, ...), np.flatten() 1차원으로 변경
# np.ndim, np.shape, np.dype, np.dtpye.name, np.size